// Copyright (c) 2026 Matthew / FracturedStars. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "UniverseTypes.h"
#include "LogisticsTypes.generated.h"

/**
 * Sprint 6: NPC Logistics & Trade Network Types
 * 
 * Core principle: Goods never teleport. All economic movement flows through logistics.
 * 
 * This system creates the first true living-universe behavior by physically moving
 * goods through the jump network using NPC cargo ships.
 */

// ============================================================================
// TRADE REQUESTS & EXPORT OPPORTUNITIES
// ============================================================================

/**
 * Trade request priority levels
 * Determines urgency of import needs
 */
UENUM(BlueprintType)
enum class ETradeRequestPriority : uint8
{
	Low			UMETA(DisplayName = "Low"),			// Minor shortage, non-essential
	Normal		UMETA(DisplayName = "Normal"),		// Standard shortage
	High		UMETA(DisplayName = "High"),		// Significant shortage
	Critical	UMETA(DisplayName = "Critical")		// Severe shortage of essential goods
};

/**
 * Trade request generated by locations with shortages
 * Represents an import demand that needs to be fulfilled
 */
USTRUCT(BlueprintType)
struct FTradeRequest
{
	GENERATED_BODY()

	// Unique request identifier
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 RequestId = -1;

	// Location requesting goods
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 SystemId = -1;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 LocationId = -1;

	// Good type needed
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	EGoodType GoodType = EGoodType::Food;

	// Quantity needed to resolve shortage
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 QuantityNeeded = 0;

	// Maximum price willing to pay per unit
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float MaxPrice = 0.0f;

	// Request priority (based on shortage severity and good importance)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	ETradeRequestPriority Priority = ETradeRequestPriority::Normal;

	// How long this request has been active (game time seconds)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	double RequestAge = 0.0;

	// Economic importance score (0.0 - 1.0)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float EconomicImportance = 0.5f;

	// Has this request been matched with a trade route?
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	bool bIsMatched = false;

	FTradeRequest()
		: RequestId(-1)
		, SystemId(-1)
		, LocationId(-1)
		, GoodType(EGoodType::Food)
		, QuantityNeeded(0)
		, MaxPrice(0.0f)
		, Priority(ETradeRequestPriority::Normal)
		, RequestAge(0.0)
		, EconomicImportance(0.5f)
		, bIsMatched(false)
	{}
};

/**
 * Export opportunity generated by locations with surpluses
 * Represents available goods for sale and export
 */
USTRUCT(BlueprintType)
struct FExportOpportunity
{
	GENERATED_BODY()

	// Unique opportunity identifier
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 OpportunityId = -1;

	// Location offering goods
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 SystemId = -1;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 LocationId = -1;

	// Good type available for export
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	EGoodType GoodType = EGoodType::Food;

	// Total quantity available in surplus
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 QuantityAvailable = 0;

	// Current market price per unit
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float MarketPrice = 0.0f;

	// How much of this surplus has been reserved for trade routes
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 QuantityReserved = 0;

	// Export priority (higher surplus = higher priority)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float ExportPriority = 0.5f;

	FExportOpportunity()
		: OpportunityId(-1)
		, SystemId(-1)
		, LocationId(-1)
		, GoodType(EGoodType::Food)
		, QuantityAvailable(0)
		, MarketPrice(0.0f)
		, QuantityReserved(0)
		, ExportPriority(0.5f)
	{}
};

// ============================================================================
// TRADE ROUTES
// ============================================================================

/**
 * Trade route status
 */
UENUM(BlueprintType)
enum class ETradeRouteStatus : uint8
{
	Pending		UMETA(DisplayName = "Pending"),		// Route created, waiting for ship assignment
	Active		UMETA(DisplayName = "Active"),		// Ship assigned and in transit
	Completed	UMETA(DisplayName = "Completed"),	// Delivery completed successfully
	Failed		UMETA(DisplayName = "Failed"),		// Route failed (no path, source depleted, etc.)
	Cancelled	UMETA(DisplayName = "Cancelled")	// Route cancelled before completion
};

/**
 * Trade route
 * Represents a matched trade with path through jump network
 */
USTRUCT(BlueprintType)
struct FTradeRoute
{
	GENERATED_BODY()

	// Unique route identifier
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 RouteId = -1;

	// Source location (exporter)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 SourceSystemId = -1;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 SourceLocationId = -1;

	// Destination location (importer)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 DestinationSystemId = -1;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 DestinationLocationId = -1;

	// Good being transported
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	EGoodType GoodType = EGoodType::Food;

	// Cargo quantity
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 CargoQuantity = 0;

	// Jump path (array of SystemIds from source to destination)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	TArray<int32> JumpPath;

	// Current position in JumpPath (which system index ship is at)
	// Sprint 6: Tracks ship movement through jump network
	// 0 = at source, JumpPath.Num()-1 = at destination
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 RouteProgress = 0;

	// Estimated profit for this route (credits)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float EstimatedProfit = 0.0f;

	// Route distance (jump count)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 RouteDistance = 0;

	// Estimated transit time (game time seconds)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float EstimatedTransitTime = 0.0f;

	// Route status
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	ETradeRouteStatus Status = ETradeRouteStatus::Pending;

	// Assigned logistics company ID
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 AssignedCompanyId = -1;

	// Assigned cargo ship ID
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 AssignedShipId = -1;

	// Route creation time
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	double CreationTime = 0.0;

	// Completion time (when delivery occurred)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	double CompletionTime = 0.0;

	FTradeRoute()
		: RouteId(-1)
		, SourceSystemId(-1)
		, SourceLocationId(-1)
		, DestinationSystemId(-1)
		, DestinationLocationId(-1)
		, GoodType(EGoodType::Food)
		, CargoQuantity(0)
		, RouteProgress(0)
		, EstimatedProfit(0.0f)
		, RouteDistance(0)
		, EstimatedTransitTime(0.0f)
		, Status(ETradeRouteStatus::Pending)
		, AssignedCompanyId(-1)
		, AssignedShipId(-1)
		, CreationTime(0.0)
		, CompletionTime(0.0)
	{}
};

// ============================================================================
// LOGISTICS COMPANIES
// ============================================================================

/**
 * NPC Logistics Company
 * Simulation entity representing a cargo hauling organization
 * No visual representation required (simulation only)
 */
/**
 * FACTION LOGISTICS FLEET
 * Sprint 6-7: Each faction owns and operates its own cargo fleet
 * Ships ONLY serve their owning faction's economy - no cross-faction trade
 * Factions must manage fleet capacity, maintenance, and expansion
 * 
 * Ships are stored in ULogisticsSubsystem::FleetRegistry (TMap<int32, FShipData>)
 * Companies reference ships by ID using OwnedShipIds array
 */
USTRUCT(BlueprintType)
struct FLogisticsCompany
{
	GENERATED_BODY()

	// Unique company identifier
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 CompanyId = -1;

	// Company name (will become "Faction X Logistics Division")
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	FString Name;

	// FACTION OWNERSHIP: Which faction owns this fleet
	// Sprint 7: Ships ONLY trade within their faction's economy
	// -1 = independent (temporary, for Sprint 6 testing)
	// 0+ = faction-owned logistics division
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 OwningFactionId = -1;

	// Home system where fleet is based (faction capital or major hub)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 HomeSystemId = 0;

	// Ships owned by this company (references to FleetRegistry)
	// All ships use FShipData from Ship/ShipData.h
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	TArray<int32> OwnedShipIds;

	// FACTION BUDGET: Credits allocated by faction for fleet operations
	// Used for ship purchases, repairs, maintenance, upkeep
	// Faction must allocate resources to expand/maintain fleet
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float Credits = 100000.0f;

	// Number of active (operational) ships
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 ActiveShipCount = 0;

	// Total cargo delivered (all time, in units)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int64 TotalCargoDelivered = 0;

	// Total revenue earned (all time, in credits)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float TotalRevenue = 0.0f;

	// Total deliveries completed
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 TotalDeliveries = 0;

	// Average delivery time (game time seconds)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float AverageDeliveryTime = 0.0f;

	// Reputation placeholder (for future faction/contract systems)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float Reputation = 0.5f;

	FLogisticsCompany()
		: CompanyId(-1)
		, Credits(100000.0f)
		, OwningFactionId(-1)
		, HomeSystemId(0)
		, ActiveShipCount(0)
		, TotalCargoDelivered(0)
		, TotalRevenue(0.0f)
		, TotalDeliveries(0)
		, AverageDeliveryTime(0.0f)
		, Reputation(0.5f)
	{}

	FLogisticsCompany(int32 InId, const FString& InName)
		: CompanyId(InId)
		, Name(InName)
		, Credits(100000.0f)
		, ActiveShipCount(0)
		, TotalCargoDelivered(0)
		, TotalRevenue(0.0f)
		, TotalDeliveries(0)
		, AverageDeliveryTime(0.0f)
		, Reputation(0.5f)
		, HomeSystemId(0)
		, OwningFactionId(-1)
	{}
};

// ============================================================================
// CARGO SHIPS - NOW USING FShipData FROM Ship/ShipData.h
// ============================================================================

/**
 * NOTE: FCargoShip has been REMOVED in favor of the real ship system.
 * 
 * All logistics ships now use FShipData from Ship/ShipData.h which provides:
 * - OwnerId + OwnerType for faction ownership
 * - Component-based architecture with wear/condition tracking
 * - Cargo system via CargoInventory TMap<EGoodType, int32>
 * - Fuel, crew, power, shields, weapons
 * - Hull condition tracking
 * - Status tracking (Docked, InTransit, Active, Disabled, Destroyed)
 * 
 * Ships are stored in ULogisticsSubsystem::FleetRegistry as TMap<int32, FShipData>
 * and referenced by ID through FLogisticsCompany::OwnedShipIds.
 * 
 * This eliminates duplication and ensures logistics ships use the same architecture
 * as player ships, NPC ships, and pirate ships.
 */

// ============================================================================
// STATISTICS & REPORTING
// ============================================================================

/**
 * Trade route performance statistics
 * Tracks volume and frequency of specific trade lanes
 */
USTRUCT(BlueprintType)
struct FTradeRouteStatistics
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 SourceSystemId = -1;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 DestinationSystemId = -1;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 TotalShipments = 0;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int64 TotalCargoMoved = 0;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float TotalValue = 0.0f;

	FTradeRouteStatistics()
		: SourceSystemId(-1)
		, DestinationSystemId(-1)
		, TotalShipments(0)
		, TotalCargoMoved(0)
		, TotalValue(0.0f)
	{}
};

/**
 * Good trade statistics
 * Tracks volume and value of specific goods traded
 */
USTRUCT(BlueprintType)
struct FGoodTradeStatistics
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	EGoodType GoodType = EGoodType::Food;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int64 TotalUnitsTraded = 0;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float TotalValue = 0.0f;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 TotalShipments = 0;

	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float AveragePrice = 0.0f;

	FGoodTradeStatistics()
		: GoodType(EGoodType::Food)
		, TotalUnitsTraded(0)
		, TotalValue(0.0f)
		, TotalShipments(0)
		, AveragePrice(0.0f)
	{}
};

/**
 * Logistics system statistics
 * Universe-wide trade metrics and performance data
 */
USTRUCT(BlueprintType)
struct FLogisticsStatistics
{
	GENERATED_BODY()

	// Total cargo moved (all time, all goods)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int64 TotalCargoMoved = 0;

	// Total number of completed deliveries
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 TotalDeliveries = 0;

	// Total trade value (all time, in credits)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float TotalTradeValue = 0.0f;

	// Average delivery distance (jump count)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	float AverageDeliveryDistance = 0.0f;

	// Active trade routes (currently in transit)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 ActiveRouteCount = 0;

	// Active cargo ships
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	int32 ActiveShipCount = 0;

	// Per-route statistics (top routes by volume)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	TArray<FTradeRouteStatistics> TopRoutes;

	// Per-good statistics (most traded goods)
	UPROPERTY(BlueprintReadOnly, Category = "Logistics")
	TArray<FGoodTradeStatistics> MostTradedGoods;

	FLogisticsStatistics()
		: TotalCargoMoved(0)
		, TotalDeliveries(0)
		, TotalTradeValue(0.0f)
		, AverageDeliveryDistance(0.0f)
		, ActiveRouteCount(0)
		, ActiveShipCount(0)
	{}
};
